[package]
org = "binoyperies"
name = "book_store"
version = "0.1.0"
distribution = "2201.9.2"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "com.mysql"
artifactId = "mysql-connector-j"
version = "8.1.0"
